export const LOADING_RESERVATIONS="LOADING_RESERVATIONS";
export const GET_ALL_RESERVATIONS_SUCCESS = "GET_ALL_RESERVATIONS_SUCCESS";
export const GET_ALL_RESERVATIONS_FAIL = "GET_ALL_RESERVATIONS_FAIL";


export const ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS";
export const ADD_RESERVATION_FAIL = "ADD_RESERVATION_FAIL";


export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_FAIL = "DELETE_RESERVATION_FAIL";

export const GET_ONE_RESERVATION_SUCCESS = "GET_ONE_RESERVATION_SUCCESS";
export const GET_ONE_RESERVATION_FAIL = "GET_ONE_RESERVATION_FAIL";

export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS";
export const UPDATE_RESERVATION_FAIL = "UPDATE_RESERVATION_FAIL";