export const LOADING_SALLES="LOADING_SALLES";
export const GET_ALL_SALLES_SUCCESS = "GET_ALL_SALLES_SUCCESS";
export const GET_ALL_SALLES_FAIL = "GET_ALL_SALLES_FAIL";


export const ADD_SALLE_SUCCESS = "ADD_SALLE_SUCCESS";
export const ADD_SALLE_FAIL = "ADD_SALLE_FAIL";


export const DELETE_SALLE_SUCCESS = "DELETE_SALLE_SUCCESS";
export const DELETE_SALLE_FAIL = "DELETE_SALLE_FAIL";

export const GET_ONE_SALLE_SUCCESS = "GET_ONE_SALLE_SUCCESS";
export const GET_ONE_SALLE_FAIL = "GET_ONE_SALLE_FAIL";

export const UPDATE_SALLE_SUCCESS = "UPDATE_SALLE_SUCCESS";
export const UPDATE_SALLE_FAIL = "UPDATE_SALLE_FAIL";